# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_state', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=100)),
                ('submit_time', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('nodes', models.CharField(max_length=200)),
                ('cpus_per_node', models.IntegerField(default=1)),
                ('mem_per_node', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('hostname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('cpus', models.IntegerField(default=1)),
                ('alloc_cpus', models.IntegerField()),
                ('real_mem', models.IntegerField()),
                ('alloc_mem', models.IntegerField()),
                ('tmp_disk', models.IntegerField()),
            ],
        ),
    ]
