# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurm', '0003_auto_20170515_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSnapshot',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('nodes_total', models.IntegerField()),
                ('nodes_alive', models.IntegerField()),
                ('nodes_alloc', models.IntegerField()),
                ('jobs_running', models.IntegerField()),
                ('jobs_pending', models.IntegerField()),
                ('jobs_other', models.IntegerField()),
                ('jobs_avg_qtime', models.DurationField()),
                ('cpus_total', models.IntegerField()),
                ('cpus_alloc', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
