# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurm', '0004_auto_20170522_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='slurmctld_alive',
            field=models.IntegerField(default=0),
        ),
    ]
